import { type Metadata } from "next";
import { dark } from "@clerk/themes";
import {
 ClerkProvider,
 SignInButton,
 SignUpButton,
 SignedIn,
 SignedOut,
 UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});

const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Clerk Next.js Quickstart",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <ClerkProvider appearance={{ baseTheme: dark }}>
   <html lang="en">
    <body
     className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}
    >
     <header className="bg-black z-50 flex justify-between items-center fixed top-0 inset-x-0 p-4 gap-4 h-16">
      <div className="space-x-4 flex items-center">
       <span className="font-bold text-orange-500 text-5xl">₹</span>
       <span className="font-semibold text-2xl">Fiscus</span>
      </div>
      <div className="space-x-4">
       <SignedOut>
        <SignInButton />
        <SignUpButton />
       </SignedOut>
       <SignedIn>
        <UserButton />
       </SignedIn>
      </div>
     </header>
     {children}
    </body>
   </html>
  </ClerkProvider>
 );
}
